# Generated by Django 2.1.5 on 2019-01-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(max_length=1),
        ),
    ]
