# Generated by Django 2.1.5 on 2019-01-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='started',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer Not to Say')], max_length=1),
        ),
    ]
