# Generated by Django 2.1.5 on 2019-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembership', '0002_auto_20190116_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='person',
            name='membership',
            field=models.ManyToManyField(null=True, to='clubmembership.Group'),
        ),
    ]
