# Generated by Django 2.1.5 on 2019-01-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembership', '0003_auto_20190116_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='membership',
            field=models.ManyToManyField(blank='', to='clubmembership.Group'),
        ),
    ]
