# Generated by Django 2.1.5 on 2019-01-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembership', '0004_auto_20190116_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank='', to='clubmembership.Person'),
        ),
    ]
