# Generated by Django 2.1.5 on 2019-01-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembership', '0005_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
