# Generated by Django 2.1.5 on 2019-01-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembership', '0006_remove_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('period', models.IntegerField(choices=[(7, 'WEEKLY'), (30, 'MONTHLY'), (365, 'YEARLY')])),
                ('effective', models.DateField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubmembership.Group')),
            ],
        ),
    ]
