# Generated by Django 2.1.5 on 2019-01-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembership', '0007_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ('description', 'effective')},
        ),
    ]
